---
output: github_document
---

<!-- README.md is generated from README.Rmd. Please edit that file -->

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

# STAT5385-stats-in-research

<!-- badges: start -->
<!-- badges: end -->

The goal of this repository is to make my assignments' R codes for a course I'm currently taking in Advanced Regression Analysis, titled "**Statistics in Research**" at the University of Texas at El Paso,  available to some of my classmates who requested for them for their learning. Their aim is to learn from the R codes!


To ensure there is no problem with academic dishonesty, the codes are published here some days after grades have been received for the particular assignment.


> It is my pleasure that you find these materials helpul. Feel free to point out any mistakes/inconsistencies you find therein, especially in the R codes, since "Mistakes are a fact of life. It is the response to error that counts.", as said by Mikki Giovanni.

**Click the "view code" link above, immediately before this readme file, to see the available contents if they don't show up by default**

A big thanks goes to the students who first made the request.

*Made with love!*

